### ISSUE TITLE
Some issues occur when downloading offline version of Sentinel-2 2A product

### ISSUE THREAD

**Issue by ChangpeiHe** [DHI-GRAS/creodias-finder#11]
<img width="494" alt="image" src="https://github.com/DHI-GRAS/creodias-finder/assets/126058879/da0699e8-7470-4a87-b425-bf13e6ad5655">
The file size is only 22B.

**Comment by radosuav** [comment]
This issue is most probably related to Creodias (or CDSE) and not this package. You can check with the latest code if it still exists.
