### ISSUE TITLE
Files are downloaded corrupted using download_list

### ISSUE THREAD

**Issue by DavidOSilva** [DHI-GRAS/creodias-finder#16]
I did some tests with the download_list function, I noticed that sometimes the download does not start properly for some or even all uids, that is, the execution goes straight through. In this sense, the files end up being downloaded corrupted. Is there something I don't quite understand and am overlooking?

` _ = download.download_list(uids, outdir='files', threads=min(32, os.cpu_count() + 4), show_progress=False, **CREDENTIALS)`

![Captura de tela 2024-01-14 154506](https://github.com/DHI-GRAS/creodias-finder/assets/82072686/8a70ae08-9e4f-4408-95ff-bd4cb2dab2fa)

The image highlights the corrupted file. As I mentioned sometimes all files get corrupted. There is always the option of downloading them individually, but this would take much longer. Suggestions?

**Comment by mcihadarslanoglu** [comment]
Probably it is about concurrency limit by copernicus data space. I also encountered this problem. After reducing, thread number, it seems work.

`       creodias_finder.download.download_list(ids,
                                               threads=2, # <-- change here.
                                               username=username,
                                               password=password,
                                               outdir=TMP_FOLDER)`

https://documentation.dataspace.copernicus.eu/Quotas.html
